import React from 'react';
import {observer} from 'mobx-react-lite';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import {StoreContext} from '../store';
import {getLayout} from "../components/Layout";

require('./index.less');

const Home = observer(({page}) => {
    const store = React.useContext(StoreContext);

  return (
    <div className="container-root">
      <Head>
        <title>Chris & Georgia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-root">
          {/*Links Placeholders ...*/}
          {/*<Link href="/usa"><a>USA</a></Link>*/}
          {/*<Link href="/austria"><a>Austria</a></Link>*/}

          <div className="" style={{
              position: 'absolute',
              zIndex: 100,
              margin: 'auto',
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              textAlign: 'center',
              width: '100%',
              marginTop: '25px',
              flexDirection: 'column'
          }}>
              <img src="/assets/img/logo/cg-white.png" alt="" style={{width: '200px'}}/>
              {/*<p style={{color: '#ffffff'}}>Pick a Location</p>*/}
          </div>

          <section className="gradient-overlay gradient-overlay-dark ">
              <img className="bg-image" src="assets/img/venues/fc-us-venue.jpg" alt=""/>
              <div className="container" style={{minHeight: '50vh'}}>
                  <div className="row min-vh-80 align-items-center z-index-2 position-relative text-center">
                      <div className="col-12">
                          <Link href="/usa"><a className="btn btn-primary btn-wide-md btn-md">Destination USA</a></Link>
                      </div>
                  </div>
              </div>
          </section>
          <section className="gradient-overlay gradient-overlay-dark ">
              <img className="bg-image" src="assets/img/venues/cg-at-venue.jpg" alt=""/>
              <div className="container" style={{minHeight: '50vh'}}>
                  <div className="row min-vh-80 align-items-center z-index-2 position-relative text-center">
                      <div className="col-12">
                          <Link href="/austria"><a className="btn btn-primary btn-wide-md btn-md">Destination Austria</a></Link>
                      </div>
                  </div>
              </div>
          </section>
      </main>
    </div>
  )
});

Home.getLayout = getLayout;
export default Home;

export const getServerSideProps = async (context) => {
    return {
        props: {
            page: null
        }
    }
}
