import React from 'react';
import {observer} from 'mobx-react-lite';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import {StoreContext} from '../store';
import {getLayout} from "../components/Layout";

require('./index.less');

const Home = observer(({page}) => {
    const store = React.useContext(StoreContext);

  return (
    <div className="container-root">
      <Head>
        <title>Chris & Georgia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-root">
          {/*Links Placeholders ...*/}
          {/*<Link href="/usa"><a>USA</a></Link>*/}
          {/*<Link href="/austria"><a>Austria</a></Link>*/}

          <div className="" style={{
              position: 'absolute',
              zIndex: 100,
              margin: 'auto',
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              textAlign: 'center',
              width: '100%',
              marginTop: '25px',
              flexDirection: 'column'
          }}>
              <img src="/assets/img/logo/cg-white.png" alt="" style={{width: '200px'}}/>
          </div>

          <Link href="/usa">
              <a className="root-selector">
                  <section className="gradient-overlay gradient-overlay-dark root-container ">
                      <img className="bg-image" src="assets/img/venues/fc-us-venue.jpg" alt=""/>
                      <div className="container">
                          <h1 style={{color: 'rgba(255,255,255,0.4)', position: 'absolute', zIndex: 2, bottom: 0, left: '10px', fontSize: '5rem'}}><strong>USA</strong></h1>
                      </div>
                  </section>
              </a>
          </Link>
          <Link href="/austria">
            <a className="root-selector">
              <section className="gradient-overlay gradient-overlay-dark root-container ">
                  <img className="bg-image" src="assets/img/venues/cg-at-venue.jpg" alt=""/>
                  <div className="container" style={{height: '100%'}}>
                      <h1 style={{color: 'rgba(255,255,255,0.4)', position: 'absolute', zIndex: 2, bottom: 0, right: '10px', fontSize: '5rem'}}><strong>AUSTRIA</strong></h1>

                  </div>
              </section>
            </a>
          </Link>
      </main>
    </div>
  )
});

Home.getLayout = getLayout;
export default Home;

export const getServerSideProps = async (context) => {
    return {
        props: {
            page: null
        }
    }
}
